language: python
sudo: false
cache: pip

python:
  # For branches <= 10.0, put `- "2.7.13"`
  - "3.5"

addons:
  # By default postgresql-9.1 is installed but there is issue related:
  #  https://github.com/OCA/maintainer-quality-tools/issues/432#issuecomment-281580935
  # Better use higher PostgreSQL version
  postgresql: "9.5"
  apt:
    #    sources:
    #    Search your sources alias here:
    #      https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
    packages:
      - expect-dev # provides unbuffer utility
#     Search your packages here:
#       https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
#     For wkhtmltopdf, see the env section below

# Sometimes complicated website repos need Compass & SaSS:
#before_install:
#  - rvm install ruby --latest
#  - gem install bootstrap-sass
#  - gem install compass --pre

env:
  global:
    - VERSION="12.0" TESTS="0" LINT_CHECK="0" MAKEPOT="0"
    # Set this variable to some version existing as linux-generic build on
    # https://github.com/wkhtmltopdf/wkhtmltopdf/releases
    # if you need to install wkhtmltopdf
    # - WKHTMLTOPDF_VERSION="0.12.4"
    # Set the above to install a `wkhtmltopdf` version that is not the one provided
    # by the `pov-wkhtmltopdf` repo.
    - PHANTOMJS_VERSION="latest"
    # The above line controls the PhantomJS version that is used for JS testing.
    #   It is not necessary to include this value unless you are altering the default.
    #   Use `OS` to skip the PhantomJS upgrade & use the system version instead.
    - WEBSITE_REPO="1"
  # Use the above line to install dependencies that are required for website repos:
  # * SASS & Bootstrap-SASS
  # * Compass

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:./ci/:${PATH}
  - travis_install_nightly
  - pip3 install -r requirements.txt
  - pip3 install -r ci/requirements.txt

jobs:
  include:
    - env: LINT_CHECK="1"
      script:
        - export PYTHONPATH=./src/:$PYTHONPATH
        - pylint --rcfile=ci/pylint-rc src/odootools/
        - pylint --rcfile=ci/pylint-rc scripts/
        - pylint --rcfile=ci/pylint-rc tests/

    - env: ODOO_REPO="odoo/odoo"
      script:
        - chmod +x ci/odootools_run_tests
        - odootools_run_tests

    - env: ODOO_REPO="OCA/OCB"
      script:
        - chmod +x ci/odootools_run_tests
        - odootools_run_tests

after_success:
  - travis_after_tests_success
