#!/usr/bin/env python
"""
Script to select and run tests depending on environment
"""

import logging
import os
import sys
import unittest
import pkgutil
import importlib


def get_server_path():
    """
    Get The location of odoo installation (Travis)
    """
    odoo_org, odoo_repo = os.environ.get("ODOO_REPO", "odoo/odoo").split("/")
    odoo_version = os.environ.get("VERSION").replace("/", "-")

    server_dirname = "%s-%s" % (odoo_repo, odoo_version)
    server_path = os.path.join(os.environ.get("HOME", "~/"), server_dirname)
    return server_path


if __name__ == "__main__":

    # Check if in Travis or not

    TRAVIS_CI = False
    if len(sys.argv) == 2:
        TRAVIS_CI = sys.argv[1] == "TRAVIS"

    # init logging
    logging.basicConfig()
    logging.getLogger().setLevel(logging.DEBUG)

    # adds odoo & odootools to PATH
    if TRAVIS_CI:
        ODOO_PATH = get_server_path()
        sys.path.append(ODOO_PATH)
        sys.path.append("./src/")
        sys.path.insert(0, "./")

    # prepare testSuite
    LOADER = unittest.TestLoader()
    RUNNER = unittest.TextTestRunner()
    SUITE = unittest.TestSuite()

    # discover tests
    importlib.import_module("tests", ".")
    for module in pkgutil.iter_modules(["./tests"]):
        module_name = module[1]
        if module_name.startswith("test"):
            mod = importlib.import_module(".{}".format(module_name), "tests")
            run = True
            if "TRAVIS_TEST" in dir(mod):
                run = mod.TRAVIS_TEST == "Yes"
            if run and "_addTestsToSuite" in dir(mod):
                mod._addTestsToSuite(SUITE)
            elif run:
                SUITE.addTest(LOADER.loadTestsFromModule(mod))
    # run tests
    results = RUNNER.run(SUITE)
    if results.failures or results.errors:
        sys.exit(1)
    else:
        sys.exit(0)
